//img_resizer
(function(){'origin:http://fmdesign.forumotion.com/t544-image-resizer#8305';\A \A window.fa_img_resizer = {\A max_width : 400,// maximum image width (400px)\A max_height : 250,// maximum image height (250px)\A \A selector : '.post-contents img',// where images should be resized\A \A options : {\A bar : true,// resized image options bar\A toggler : true,// Enlarge / Reduce Image\A full_size : true,// Show full size\A download : true,// Download image link\A lightbox : true // lightbox effect\A },\A \A // texts\A lang : {\A full_size : '<i class="fa fa-picture-o"></i> عرض الحجم الكامل',\A enlarge : '<i class="fa fa-eye-slash"></i> تكبير الصورة',\A reduce : '<i class="fa fa-eye"></i> تصغير الصورة',\A download : '<i class="fa fa-cloud-download"></i> تحميل الصورة',\A tooltip : 'إضغط لرؤية الصورة الكاملة'\A },\A \A // resize all images inside the "resizeIn" elements\A resize : function() {\A for (var a = $(fa_img_resizer.selector).not('.mention-ava'),i = 0,j = a.length; i < j; i++) {\A if (!a[i].alt && (a[i].naturalWidth > fa_img_resizer.max_width || a[i].naturalHeight > fa_img_resizer.max_height)) {\A a[i].className += ' fa_img_reduced';\A \A // make the image a "link" if it's not wrapper with one if (fa_img_resizer.options.lightbox && a[i].parentNode.tagName != 'A') { a[i].style.cursor = pointer;aititle:fa_img_resizer.lang.tooltip;aionclick:function() { fa_img_resizer.lightbox(this)}// create the resize bar
if (fa_img_resizer.options.bar){(aiparentnodetagname:= A ? a[i].parentNode : a[i]).insertAdjacentHTML(beforebegin,'<div class="fa_img_resizer" style="width:' + (a[i].width - 8) + 'px;">'+ (fa_img_resizer.options.toggler ? '<a class="fa_img_enlarge" href="#" onclick="fa_img_resizer.toggle(this); return false;">' + fa_img_resizer.lang.enlarge + '</a>' : '')+ (fa_img_resizer.options.full_size ? '<a class="fa_img_full" href="/viewimage.forum?u=' + a[i].src + '" target="_blank">' + fa_img_resizer.lang.full_size + '</a>' : '')+ (fa_img_resizer.options.download && !/Firefox/.test(navigator.userAgent) && 'download' in document.createElement(A) ? '<a class="fa_img_download" href="' + a[i].src + '" target="_blank" download>' + fa_img_resizer.lang.download + '</a>' : '')+ '</div>')},// toggle between enlarged and reduced image sizes
toggle : function(that){varimg:that.parentNode.nextSibling;ifimgtagname:= A) { img = img.getElementsByTagName(IMG)[0]}if (/fa_img_reduced/.test(img.className)){thatinnerhtml:fa_img_resizer.lang.reduce;thatclassname:fa_img_reduce;imgclassname:img.className.replace(/fa_img_reduced/,'fa_img_enlarged')}else{thatinnerhtml:fa_img_resizer.lang.enlarge;thatclassname:fa_img_enlarge;imgclassname:img.className.replace(/fa_img_enlarged/,'fa_img_reduced')},// lightbox effect
lightbox : function(that){varfrag:document.createDocumentFragment(),overlay = $('<div id="fa_img_lb_overlay" />')[0],img = $('<img id="fa_img_lb_image" src="' + that.src + '" />')[0];overlayonclick:fa_img_resizer.kill_lightbox;imgonclick:fa_img_resizer.kill_lightbox;documentbodystyleoverflow:hidden;imgstylemargintop:- + (img.height / 2) + px;imgstylemarginleft:- + (img.width / 2) + px},// kill the lightbox
kill_lightbox : function(){varoverlay:document.getElementById(fa_img_lb_overlay),img = document.getElementById(fa_img_lb_image)}
//overlay
var overlay = function (){astylecsstext:b;aid:overlay;ffocusfunctionee:document.getElementById(quick_reply);g:document.getElementById(overlay);astyledisplay:block;estylezindex:1000;estyleposition:relative;fblurfunctiongstyledisplay:none});
document.addEventListener(keyup,function (e){ifekeycode:== 27) { f.blur()}                        
//toast                        
function toast(text){varcontainer:$(document.createElement(div));varmessage:$(document.createElement(div))}                        

 //اشعار عند الدخول                                            
function wipeout() {
  setTimeout(function() {
    $(".ps-toast").removeClass("bounceInRight").addClass("bounce");
    setTimeout(function() {
      $(".ps-toast").addClass("bounceOutRight");
    }, 4000);
  }, 5000);
}
wipeout();

//Prefix-tag
 (function ($){vartags:[ {tag: JAVASCRIPT,background: #ff0100},{tag:'HTML ',background: #1bff00;tag:css,background: #06f;tag:تومبلايت,background: #f09;tag:اخبار,background: #ff002f;tag:كتاب,background: #00c4ff;tag:تكويد,background: #00ff72;tag:ارشفة,background: #7aff00;tag:مساعدة,background: #ffe000;tag:تصميم,background: #c000ff;tag:اسلامى,background: #000;tag:شرح,background: #3f00ff}];
$(function (){varcounter:1;iflocationpathname:== /post && $('form input[name="subject"]').length > 0) { // Criar a zona para colocar-se os inputs: var $textarea = $(#textarea_content);vartitle:$('form [name="subject"]');varzone:$([ '<div class="fa-icon-selector">',' <div class="fa-icon-selector-inner">',' </div>','</div>',].join(\n)) .prependTo($textarea);$eachtagsfunctionindextagdivclass:fa-tag-form-group>',\A ' <input type=radio class=select-tag-input name=select-tag-radio id="tag-input-' + counter + '" data-tag="' + tag.tag + '" />',\A ' <label for="tag-input-' + counter + '" class=fa-tag-label>' + tag.tag + '</label>',\A '</div>',\A ].join('n'))\A .appendTo($appendZone)\A ;\A \A counter++;\A });\A \A // Fonction pour se concentrer sur une entrée X si c'est l'étiquette d'un sujet X: if (/^\[.*\]/gi.test($title.val())) { $title.val().replace(/^\[(.*)\]/gi,function (find,match) { $([data-tag=" + match + '"]').prop(checked,true); })}// Déclencheur pour ajouter / éditer le préfixe dans l'entrée de titre:\A          $zone\A            .find('input.select-tag-input')\A              .on('focus', function () {\A                setPrefix($(this).attr('data-tag'));\A              })\A          ;\A     \A          // Fonction pour définir / modifier le préfixe:\A          var setPrefix = function (prefix) {\A     \A            if (/^\[.*\]/gi.test($title.val())) {\A              $title.val($title.val().replace(/^\[.*\]/gi, function () {\A                return '[' + prefix + ']';\A              }));\A             \A              return;\A            }\A           \A             $title.val('[' + prefix + '] ' + $title.val().trim());\A          };\A        }\A     \A        /**\A        * Partie 2.\A        * Remplacer l'étiquette entre les parenthèses avec un vrai tag:
*/
var $link = $(a[href^="/t"]);
$link.each(function (){varthis:$(this);$eachtagsfunctionindextagvarregex:new RegExp (\\[ + tag.tag + '\\]','gim');vartext:$this.text()}
